spring:
  application:
    name: employee-service
  config:
    import: "optional:configserver:http://localhost:8088"
    
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Suresh@123
    url: jdbc:mysql://localhost:3306/testdb
    username: root
